# Generated by Django 5.1.7 on 2025-04-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_type',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='service_areas',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='specialties',
        ),
    ]
