# Generated by Django 5.1.7 on 2025-04-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_agent_agent_type_remove_agent_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
