# Generated by Django 5.1.7 on 2025-03-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, help_text='S3 path to company logo', max_length=255, null=True, verbose_name='Company Logo'),
        ),
    ]
