# Generated by Django 5.1.7 on 2025-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='street',
            new_name='street_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='number',
            new_name='street_number',
        ),
        migrations.AddField(
            model_name='company',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
