# Generated by Django 5.1.7 on 2025-04-20 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindeUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kinde_user_id', models.CharField(db_index=True, help_text='Unique user ID provided by Kinde.', max_length=255, unique=True)),
                ('email', models.EmailField(help_text="User's email address, typically from Kinde.", max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user is considered active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this Kinde user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='kinde_users', to='tenant.client')),
            ],
            options={
                'verbose_name': 'Kinde User',
                'verbose_name_plural': 'Kinde Users',
                'ordering': ['tenant', 'email'],
            },
        ),
    ]
