# Generated by Django 5.1.7 on 2025-04-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinde_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindeuser',
            name='kinde_user_id',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Unique user ID provided by Kinde (null until first login).', max_length=255, null=True, unique=True),
        ),
    ]
