# Generated by Django 5.1.7 on 2025-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinde_auth', '0002_alter_kindeuser_kinde_user_id'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindeuser',
            options={'ordering': ['email'], 'verbose_name': 'Kinde User', 'verbose_name_plural': 'Kinde Users'},
        ),
        migrations.RemoveField(
            model_name='kindeuser',
            name='tenant',
        ),
        migrations.AddField(
            model_name='kindeuser',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Tenants this Kinde user has access to.', related_name='kinde_users', to='tenant.client'),
        ),
    ]
