# Generated by Django 5.1.7 on 2025-03-24 11:10

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunSQL(
            # Forward SQL - safely try to remove name column if it exists
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'account_user' 
                    AND column_name = 'name'
                ) THEN
                    ALTER TABLE account_user DROP COLUMN name;
                END IF;
            END $$;
            """,
            # Reverse SQL - add name column back if needed
            """
            ALTER TABLE account_user ADD COLUMN IF NOT EXISTS name varchar(255) DEFAULT '';
            """
        ),
    ]
