# Generated by Django 5.1.7 on 2025-03-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, help_text='S3 path to user avatar', max_length=255, null=True),
        ),
    ]
