# Generated by Django 5.1.7 on 2025-04-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('client', 'Client'), ('employee', 'Employee')], help_text='Type of the user profile (Agent, Client, or Employee)', max_length=10, null=True),
        ),
    ]
