# Generated by Django 5.1.7 on 2025-04-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
