# Generated by Django 5.1.7 on 2025-04-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_staff_user_is_tenant_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether this user has all permissions without explicitly assigning them.'),
        ),
    ]
