# Generated by Django 5.1.7 on 2025-03-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='emergency_contact_name',
            new_name='emergency_contact_first_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
