# Generated by Django 5.1.7 on 2025-04-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_is_superuser'),
        ('client', '0004_alter_clientcontract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_profiles', to='client.client'),
        ),
    ]
