# Generated by Django 5.1.7 on 2025-04-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_employeeprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
