# Generated by Django 5.1.7 on 2025-04-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_employeeprofile_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='client_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
