# Generated by Django 5.1.7 on 2025-04-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_clientprofile_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='license_number',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='abn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
