# Generated by Django 5.1.7 on 2025-04-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='tax_id',
            new_name='abn',
        ),
        migrations.RemoveField(
            model_name='client',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='industry',
        ),
    ]
