# Generated by Django 5.1.7 on 2025-04-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientContact',
            new_name='ClientContract',
        ),
    ]
