# Generated by Django 5.1.7 on 2025-04-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_tax_id_client_abn_remove_client_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.CharField(blank=True, help_text='S3 path to client logo', max_length=255, null=True, verbose_name='Client Logo'),
        ),
    ]
