# Generated by Django 5.1.7 on 2025-04-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_clientcontact_clientcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2011-01-01 01:01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
