# Generated by Django 5.1.7 on 2025-04-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientcontract_created_at_clientcontract_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='client.client'),
        ),
    ]
