# Generated by Django 5.1.7 on 2025-04-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientcontract_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwarehouse',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientwarehouse',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clientwarehouse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
