# Generated by Django 5.1.7 on 2025-04-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientwarehouse_first_name_clientwarehouse_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientwarehouse',
            name='contact_name',
        ),
    ]
