# Generated by Django 5.1.7 on 2025-03-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='unit',
        ),
    ]
