# Generated by Django 5.1.7 on 2025-03-28 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_user_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_user_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('included_users', models.PositiveIntegerField(default=1, help_text='Number of users included in the base price')),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='billing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='paid_user_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users the tenant has paid for'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='tenant.subscriptionplan'),
        ),
    ]
